version: "3.8"
services:
  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -b '0.0.0.0'"
    volumes:
      - ".:/importer"
    ports:
      - "3000:3000"
    depends_on:
      - db
      - redis
    environment:
      - REDIS_URL=redis://redis:6379/0
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/mindapp_development

  sidekiq:
    build: .
    command: bundle exec sidekiq
    volumes:
      - ".:/importer"
    depends_on:
      - db
      - redis
    environment:
      - REDIS_URL=redis://redis:6379/0

  db:
    image: postgres
    volumes:
      - pg_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=mindapp_development

  redis:
    image: redis:latest
    volumes:
      - redisdata:/data

volumes:
  pg_data:
    driver: local
  redisdata:
    driver: local